# Generated by Django 2.0.2 on 2018-06-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_net_amount_payable_details_paymentdetails_royaltydetails_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net_amount_payable_details',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='royaltydetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
        migrations.DeleteModel(
            name='Net_amount_Payable_Details',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.DeleteModel(
            name='RoyaltyDetails',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
