# Generated by Django 2.0.2 on 2018-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180617_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net_amount_payable_details',
            name='user',
        ),
        migrations.RemoveField(
            model_name='royaltydetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='closing_stock',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='international_sales',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='royalty_amount',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='royalty_rate',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='total_sales',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_details',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Net_amount_Payable_Details',
        ),
        migrations.DeleteModel(
            name='RoyaltyDetails',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
