# Generated by Django 2.0.2 on 2018-06-17 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_auto_20180617_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=30)),
                ('title_id', models.IntegerField(null=True)),
                ('title_isbn', models.CharField(max_length=20)),
                ('edition', models.CharField(max_length=20)),
                ('price', models.FloatField(null=True)),
                ('version', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
