# Generated by Django 2.0.2 on 2018-06-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0015_auto_20180617_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card_no', models.CharField(max_length=20)),
                ('aadhar_card_no', models.CharField(max_length=20)),
                ('permanentaddress', models.CharField(blank=True, max_length=100)),
                ('permanentcity', models.CharField(max_length=20)),
                ('permanentstate', models.CharField(max_length=20)),
                ('permanentpin', models.CharField(max_length=20)),
                ('permanentcountry', models.CharField(max_length=20)),
                ('postaladdress', models.CharField(blank=True, max_length=100)),
                ('postalcity', models.CharField(max_length=20)),
                ('postalstate', models.CharField(max_length=20)),
                ('postalpin', models.CharField(max_length=20)),
                ('postalcountry', models.CharField(max_length=20)),
                ('mobile1', models.CharField(max_length=20)),
                ('mobile2', models.CharField(max_length=20)),
                ('personalemail', models.CharField(max_length=20)),
                ('office_email', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
