# Generated by Django 2.0.2 on 2018-06-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180618_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookData',
        ),
    ]
