# Generated by Django 2.0.2 on 2018-06-21 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0021_auto_20180621_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(null=True)),
                ('copies_printed', models.IntegerField(null=True)),
                ('total_copies', models.IntegerField(null=True)),
                ('no_of_specimen_copies_issued', models.IntegerField(null=True)),
                ('defective_copies', models.IntegerField(null=True)),
                ('domestic_sales', models.IntegerField(null=True)),
                ('international_sales', models.IntegerField(null=True)),
                ('total_sales', models.IntegerField(null=True)),
                ('closing_stock', models.IntegerField(null=True)),
                ('royalty_rate', models.IntegerField(null=True)),
                ('royalty_amount', models.IntegerField(null=True)),
                ('total_royalty', models.FloatField(null=True)),
                ('advances', models.FloatField(null=True)),
                ('tds', models.FloatField(null=True)),
                ('net_amount_payable', models.FloatField(null=True)),
                ('payment_details', models.CharField(max_length=100)),
                ('title_name', models.CharField(max_length=30)),
                ('title_id', models.IntegerField(null=True)),
                ('title_isbn', models.CharField(max_length=20)),
                ('edition', models.CharField(max_length=20)),
                ('price', models.FloatField(null=True)),
                ('version', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card_no', models.CharField(max_length=20)),
                ('aadhar_card_no', models.CharField(max_length=20)),
                ('permanentaddress', models.CharField(blank=True, max_length=100)),
                ('permanentcity', models.CharField(max_length=20)),
                ('permanentstate', models.CharField(max_length=20)),
                ('permanentpin', models.CharField(max_length=20)),
                ('permanentcountry', models.CharField(max_length=20)),
                ('postaladdress', models.CharField(blank=True, max_length=100)),
                ('postalcity', models.CharField(max_length=20)),
                ('postalstate', models.CharField(max_length=20)),
                ('postalpin', models.CharField(max_length=20)),
                ('postalcountry', models.CharField(max_length=20)),
                ('mobile1', models.CharField(max_length=20)),
                ('mobile2', models.CharField(max_length=20)),
                ('personalemail', models.CharField(max_length=20)),
                ('office_email', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
