# Generated by Django 2.0.2 on 2018-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_bookdata_personal_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookdata',
            table='bookdata',
        ),
    ]
