# Generated by Django 2.0.2 on 2018-06-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20180621_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='Personal_details',
        ),
    ]
