# Generated by Django 2.0.2 on 2018-06-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20180622_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='Personal_details',
        ),
    ]
